[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-toml" },
    { id = "check-merge-conflict" },
#    { id = "no-commit-to-branch", args = ["--branch", "main"] },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.6.14"
hooks = [
    { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.9.10"
hooks = [
    { id = "ruff", args = ["--fix"] },
    { id = "ruff-format" },
]
